###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "test1",
  "password": "test1",
  "gender": "FEMALE"
}

###
GET http://localhost:8080/api/v1/auth/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJpZCI6IjA4MGIwMDZjLTc3MjAtNDUwMC1iODhhLTY0NTkzOTRjMjE1YiIsImlhdCI6MTczMTY2OTYzNCwiaXNzIjoiV2VIZXJlIn0.Dy4riM1GSVtIpTrF4WW5fjntmDY1qXnVpgJiQVDk9M8

###
POST http://localhost:8080/api/v1/friendships
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJpZCI6IjA4MGIwMDZjLTc3MjAtNDUwMC1iODhhLTY0NTkzOTRjMjE1YiIsImlhdCI6MTczMTY2OTYzNCwiaXNzIjoiV2VIZXJlIn0.Dy4riM1GSVtIpTrF4WW5fjntmDY1qXnVpgJiQVDk9M8
Content-Type: application/json

{
  "hashtag": "9eb68"
}

###
GET http://localhost:8080/api/v1/friendships
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJpZCI6IjIzMmI2MDAyLTcwYjYtNGJjNS04ZjJhLTIxZjgzZThkZGY3MyIsImlhdCI6MTczMTY2OTgzOSwiaXNzIjoiV2VIZXJlIn0.z1LwSuoJM_sC5oNhsyANSu8YXyikooMYFs4bMBs7o_8

###
GET http://localhost:8080/api/v1/friendships/pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJpZCI6IjIzMmI2MDAyLTcwYjYtNGJjNS04ZjJhLTIxZjgzZThkZGY3MyIsImlhdCI6MTczMTY2OTgzOSwiaXNzIjoiV2VIZXJlIn0.z1LwSuoJM_sC5oNhsyANSu8YXyikooMYFs4bMBs7o_8

###
POST http://localhost:8080/api/v1/friendships/:friendshipId/accept?
    friendshipId=d7012469-f246-4e04-b5b2-748c34ed8fe1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJpZCI6IjIzMmI2MDAyLTcwYjYtNGJjNS04ZjJhLTIxZjgzZThkZGY3MyIsImlhdCI6MTczMTY2OTgzOSwiaXNzIjoiV2VIZXJlIn0.z1LwSuoJM_sC5oNhsyANSu8YXyikooMYFs4bMBs7o_8

###
GET http://localhost:8080/api/v1/account/genders

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "test1",
  "password": "test1"
}