###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "test3",
  "password": "test3",
  "gender": "FEMALE"
}

###
GET http://localhost:8080/api/v1/auth/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJpZCI6ImFjZDZmODllLTMxMjYtNGQxNS04MTQ3LWM5Y2I4NWJjYTMxZSIsImlhdCI6MTcyNzIxMzYyMywiaXNzIjoiV2VIZXJlIn0.rq7opgRUWKAlWeSXBJ6hG0S3h10OjtMauWd_yXFvy6g

###
POST http://localhost:8080/api/v1/friendships
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJpZCI6ImFjZDZmODllLTMxMjYtNGQxNS04MTQ3LWM5Y2I4NWJjYTMxZSIsImlhdCI6MTcyNzIxNTExNiwiaXNzIjoiV2VIZXJlIn0.bC6sAkb_b78XepyKLs1CPXCf3Un1w6EKs52ZOH-L7LU
Content-Type: application/json

{
  "hashtag": "42dsa"
}

###
GET http://localhost:8080/api/v1/account/genders

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}